---
- hosts: all

- name: Include Linux Common playbook
  import_playbook: ../../../common/os/linux/playbook.yml

- name: Linux Desktop Playbook
  hosts: all
  become: false
  vars_files:
    - ../shared/vars.yml
    - vars.yml
  vars_prompt:
    - name: "USER"
      prompt: "Please enter your User name"
      private: yes
    - name: "HOME"
      prompt: "Please enter your HOME dir"

  environment:
    NPM_CONFIG_PREFIX: "{{ HOME }}/.npm-global"
    NFANCURVE_PATH: "$HOME/nfancurve"
    PATH: "/usr/local/bin:/snap/bin:$HOME/.local/bin:{{ ansible_env.PATH }}"
    MOZ_USE_OMTC: 1

  tasks:
    - import_tasks: tasks.yml
    # Post-installation
    - import_tasks: ../shared/unix_post-task.yml
    - import_tasks: post-task.yml
    # Binary packages
    - import_tasks: ../../../common/os/shared/unix_binary-task.yml
      when: binaries is defined and binaries|length > 0
