---
# VSCodium
- name: Linking VSCodium Settings on Linux
  file:
    src: "~/Desktop/config/dotfiles/Library/Application Support/VSCodium"
    dest: "~/Desktop/config/dotfiles/.config/VSCodium"
    state: link
  retries: 1
  register: vscodium_debian_link
  until: vscodium_debian_link.attempts == 1
