---
- name: macOS Server Playbook
  hosts: all
  gather_facts: yes
  become: false

  vars_files:
    - ../shared/vars.yml
  vars_prompt:
    - name: "USER"
      prompt: "Please enter your User name"
      private: yes
    - name: "SUDO_PASS"
      prompt: "Please enter your SUDO password"
      private: yes

  environment:
    NPM_CONFIG_PREFIX: "~/.npm-global"
    MOZ_USE_OMTC: 1

  pre_tasks:
    # Pre-installation steps
    - import_tasks: ../../../common/os/shared/unix_pre-task.yml
    - import_tasks: ../shared/unix_pre-task.yml
  tasks:
    - import_tasks: ../../../common/os/mac/tasks.yml
    # Post-installation
    - import_tasks: ../../../common/os/shared/unix_post-task.yml
    - import_tasks: ../shared/post-task.yml
