---
  dependencies:
    - role: gantsign.visual-studio-code-extensions
      users:
        - username: dalisoft
          visual_studio_code_extensions:
            - ms-azuretools.vscode-docker
            - mikestead.dotenv
            - editorconfig.editorconfig
            - dbaeumer.vscode-eslint
            - mkaufman.htmlhint
            - emilast.logfilehighlighter
            - davidanson.vscode-markdownlint
            - pkief.material-icon-theme
            - eg2.vscode-npm-script
            - christian-kohler.npm-intellisense
            - techer.open-in-browser
            - ricard.postcss
            - esbenp.prettier-vscode
            - ms-python.python
            - shan.code-settings-sync
            - cssho.vscode-svgviewer
            - wayou.vscode-todo-highlight
            - ms-vscode.vscode-typescript-tslint-plugin
            - redhat.vscode-yaml

