---
- name: Ensure config folders exists
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop: "{{ ensure_folders }}"
  tags:
    - ensure-config-folders

- name: Linking initial configs
  file:
    src: "~/Desktop/config/dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    force: yes
  loop: "{{ initial_configs }}"
  retries: 1
  register: initial_config_link
  until: initial_config_link.attempts == 1
  tags:
    - link-initial-config
