---
- name: Linking initial configs
  file:
    src: "~/Desktop/config/dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    force: yes
    follow: no
  loop: "{{ initial_configs }}"
  when: initial_configs is defined
  retries: 1
  register: initial_config_link
  until: initial_config_link.attempts == 1
  tags:
    - link-initial-config

- name: Ensure config folders exists
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ USER }}"
    group: "{{ USER }}"
  loop: "{{ ensure_folders }}"
  when: ensure_folders is defined
  tags:
    - ensure-config-folders
