---
# Homebrew Taps
- name: List all Homebrew taps
  command: brew tap
  register: brew_tap_list
  changed_when: false
  check_mode: false
  tags:
    - install-brew-taps

- name: Tap all Homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_taps }}"
  register: install_brew_tap
  until: install_brew_tap is successful
  when:
    - brew_taps is defined
    - item not in brew_tap_list.stdout_lines
  tags:
    - install-brew-taps

# Homebrew packages
- name: Prepare packages
  set_fact:
    packages: "{{ (shared_packages | default([])) + (brew_packages | default([])) }}"

- name: List all Homebrew packages
  command: brew list -1
  register: brew_pkgs_list
  changed_when: false
  check_mode: false
  tags:
    - install-brew-packages

- name: Installing Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  register: install_brew_package
  until: install_brew_package is successful
  when: item not in brew_pkgs_list.stdout_lines
  tags:
    - install-brew-packages
