---
vscodium_extensions:
  # Linters
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  - mkaufman.HTMLHint
  - dprint.dprint
  # Other tools
  - redhat.vscode-yaml
  - EditorConfig.EditorConfig
  - mikestead.dotenv
  - emilast.LogFileHighlighter
  - DavidAnson.vscode-markdownlint
  - PKief.material-icon-theme
  - eg2.vscode-npm-script
  - christian-kohler.npm-intellisense
  - techer.open-in-browser
  - ricard.postcss
  - cssho.vscode-svgviewer
  - wayou.vscode-todo-highlight
  - ms-vscode.vscode-typescript-tslint-plugin
  - ms-azuretools.vscode-docker
  # Programming Languages
  - bmewburn.vscode-intelephense-client
  - jaredly.reason-vscode
  - matklad.rust-analyzer
  - ms-python.python
  - golang.go
  - llvm-vs-code-extensions.vscode-clangd

sublime_extensions_git:
  - name: GoSublime
    git_url: https://github.com/DisposaBoy/GoSublime.git
