---
npm_modules:
  - nodemon
  - http-server
  - cordova
  # - expo-cli # disable until https://github.com/expo/expo-cli/issues/2354 fixed
  - npm-check-updates
  - lerna
  - lerna-wizard
  - vercel
  - serverless
