---
pacman_packages:
  # Main tools
  - ansible
  - firefox
  - krita
  - octave
  - vlc
  - codium
  - adoptopenjdk-8-hotspot
  # - adoptopenjdk-8-headless
  # - adoptopenjdk-11-hotspot
  # - adoptopenjdk-11-headless
  # KVM packages for Virtual Machines
  - qemu-kvm
  - virtinst
  - virtualbox
  - bridge-utils
  # For Python development
  - python
  # - python-pip
  # For AI Stuffs
  - cuda
  # Addinational tools
  - cassowary
  - rust
