---
pacman_packages:
  # Improve Linux performance
  - linux-manjaro-xanmod
  # Polyfills
  - exfat-dkms-git
  # Fonts
  - ttf-fira-code
  # Programming languages
  # PHP
  - php
  - composer
  # Go
  - go
  # Python
  - python
  # Rust
  - rust
  # Mobile-dev
  - gradle
  # Other desktop tools
  - heroku-cli
  # System utilities
  - gparted
  # For some GTK themes
  # and macOS Theme dependencies
  # for Linux
  - krita
  - inkscape
  - optipng
  - sassc
  - gtk-engine-murrine
  - gtk-engines
  # Browsers
  - epiphany-browser
  # Most needed desktop apps
  - telegram-desktop
  - uget
  - vlc
  - anydesk-bin
  - octave
  - transmittion-gtk
  # Development tools
  - postman
  - gitkraken
  # Editors / IDE
  - vscodium-bin
  - android-studio
  # KVM/Packages for Virtual Machines
  - qemu
  - virtualbox
  - bridge-utils
  # For AI Stuffs
  - cuda
  # Java tools
  - jdk8-adoptopenjdk
