---
- name: Checking ST Packages Directory on macOS
  stat:
    path: ~/Library/Application Support/Sublime Text 3/Packages
  register: st_packages_dir
  when:
    - INSTALL_MODE == 'DESKTOP'

- name: Installing Rust Analyzer Language Server on macOS
  shell: |
    wget -nc \
    https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-mac
    mv rust-analyzer-mac /usr/local/bin/rust-analyzer
    chmod +x /usr/local/bin/rust-analyzer
  args:
    chdir: ~/
  when:
    - INSTALL_MODE == 'DESKTOP'
    - force_install is true or not rust_analyzer_bin.stat.exists

- name: Installing Reason Language Server on macOS
  shell: |
    wget -nc \
    https://github.com/jaredly/reason-language-server/releases/latest/download/rls-macos.zip
    unzip rls-macos.zip -d .
    mv rls-macos/reason-language-server /usr/local/bin/reason-language-server
    chmod +x /usr/local/bin/reason-language-server
    rm -rf rls-macos
    rm -rf rls-macos.zip
  args:
    chdir: ~/
  when:
    - INSTALL_MODE == 'DESKTOP'
    - force_install is true or not reason_bin.stat.exists
