---
- name: Checking GoSublime on Linux
  stat:
    path: ~/.config/sublime-text-3/Packages/GoSublime
  register: gosublime_dir

- name: Installing Rust Analyzer Language Server on Linux
  shell: |
    curl -L https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-l -o ~/lsp/bin/rust-analyzer
    chmod +x ~/lsp/bin/rust-analyzer
  when:
    - force_install_lsp is true or not rust_analyzer_bin.stat.exists

- name: Installing Reason Language Server on Linux
  shell: |
    cd ~/lsp/bin
    wget https://github.com/jaredly/reason-language-server/releases/latest/download/rls-linux.zip
    unzip rls-linux.zip -d .
    mv rls-linux/reason-language-server reason-language-server
    chmod +x reason-language-server
    rm -rf rls-linux
    rm -rf rls-linux.zip
  when:
    - force_install_lsp is true or not reason_bin.stat.exists

# VSCodium extensions
- name: VSCodium check on Linux
  stat:
    path: /usr/local/bin/code
  register: code_bin
