---
# SublimeText extensions
- name: Checking GoPLS
  stat:
    path: ~/go/bin/gopls
  register: gopls_bin

- name: Installing Golang Program Language Server
  shell: GO111MODULE=on go get golang.org/x/tools/gopls@latest
  when: force_install is true or not gopls_bin.stat.exists

- name: Checking Rust Analyzer Language Server
  stat:
    path: /usr/local/bin/rust-analyzer
  register: rust_analyzer_bin

- name: Checking Reason Language Server
  stat:
    path: /usr/local/bin/reason-language-server
  register: reason_bin

- import_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'
  tags:
    - install-editor-extensions

- name: Checking GoSublime directory
  stat:
    path: '{{ st_packages_dir.stat.path }}/GoSublime'
  register: gosublime_dir

- name: Installing GoSublime
  git:
    repo: https://github.com/DisposaBoy/GoSublime.git
    dest: "{{ gosublime_dir.stat.path }}"
  when:
    - st_packages_dir.stat.exists
    - not gosublime_dir.stat.exists
  tags:
    - install-editor-extensions

- name: Checking DockerFileLint directory
  stat:
    path: '{{ st_packages_dir.stat.path }}/SublimeLinter-contrib-dockerfilelint'
  register: dockerfilelint_dir

- name: Installing DockerFileLint
  git:
    repo: https://github.com/dalisoft/SublimeLinter-contrib-dockerfilelint.git
    dest: "{{ dockerfilelint_dir.stat.path }}"
  when:
    - st_packages_dir.stat.exists
    - not dockerfilelint_dir.stat.exists
  tags:
    - install-editor-extensions

- name: "List installed VSCodium extensions"
  command: "{{ code_bin.stat.path }} --list-extensions"
  register: vscodium_extensions_list
  changed_when: false
  check_mode: false
  when:
    - code_bin.stat.exists
  tags:
    - install-brew-cask-packages

- name: Installing VSCodium extensions
  shell: "{{ code_bin.stat.path }} --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
  register: install_vscodium_extensions
  until: install_vscodium_extensions is successful
  when:
    - code_bin.stat.exists
    - item not in vscodium_extensions_list.stdout_lines
  tags:
    - install-editor-extensions
