---
- name: Adding apt keys
  become: true
  become_user: root
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ apt_keys }}"
  register: install_apt_key
  until: install_apt_key is successful

- name: Adding apt repositories
  become: true
  become_user: root
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repos }}"
  register: install_apt_repo
  until: install_apt_repo is successful

- name: Adding custom apt repositories
  become: true
  become_user: root
  shell: "add-apt-repository '{{ item }}'"
  with_items: "{{ apt_repos_custom }}"
  register: install_apt_repo
  until: install_apt_repo is successful
  when:
    - INSTALL_MODE == 'DESKTOP'

- name: "Update apt repositories"
  become: true
  become_user: root
  apt:
    update_cache: yes
  changed_when: false
  check_mode: false

- name: Installing apt packages
  become: true
  become_user: root
  apt:
    name: "{{ apt_items }}"
    state: present
  register: install_apt_package
  until: install_apt_package is successful

- name: Create docker group
  group:
    name: "docker"
    state: present
  register: docker_post_step_1
  until: docker_post_step_1 is successful

- name: Adding user {{ USER }} to docker group
  become: true
  become_user: root
  user:
    name: "{{ USER }}"
    group: "docker"
    append: "yes"
  register: docker_post_step_2
  until: docker_post_step_2 is successful
  when: docker_post_step_1.changed

- name: Apply group change of docker
  shell: newgrp docker
  register: docker_post_step_3
  until: docker_post_step_3 is successful
  when: docker_post_step_2.changed
