---
  - name: Installing Cask items
    homebrew_cask:
      name:
        - quicklook-json
        - qlcolorcode
        - qlstephen
        - qlmarkdown
        - qlimagesize
        - font-fira-code
        - macs-fan-control
        - telegram-desktop
        - the-unarchiver
        - sublime-text
        - vscodium
        - webstorm
        - pycharm-ce
        - android-studio
        - postman
        - omnidb
        - gitkraken
        - adoptopenjdk8
        - vlc
        - docker
        - octave-app
        - folx
        - krita
        - inkscape
        - brave-browser
        - adguard
      state: upgraded
      greedy: True
    register: result
    until: result is successful
    when: homebrew_check.stat.exists
