---
- name: Install polyfill tools
  become: true
  become_user: root
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python-apt
    - exa
  register: install_apt_py
  until: install_apt_py is successful
