---
- name: Linux Common Playbook
  hosts: all
  gather_facts: yes
  become: false

  vars_files:
    - ../shared/vars.yml
    - vars.yml
  vars_prompt:
    - name: "USER"
      prompt: "Please enter your User name"
      private: yes

  environment:
    NPM_CONFIG_PREFIX: "~/.npm-global"
    MOZ_USE_OMTC: 1
    PATH: "/usr/local/bin:$HOME/.local/bin:{{ ansible_env.PATH }}:/opt/homebrew/bin"

  pre_tasks:
    # Pre-installation steps
    - import_tasks: ../shared/unix_pre-task.yml

  tasks:
    # Installation
    - import_tasks: _debian.shim.yml
      when:
        - ansible_facts['os_family'] == 'Debian'
        - ansible_facts['os_family'] != 'Pop!_OS'
        - ansible_facts['nodename'] != 'ubuntu'
    - import_tasks: _manjaro.yml
      when: ansible_facts['os_family'] == 'Archlinux'
    - import_tasks: _debian.yml
      when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Pop!_OS'
    # Post-installation
    - import_tasks: ../shared/post-task.yml
    - import_tasks: post-task.yml
