---
# Docker Post-installation steps
- name: Create docker group
  group:
    name: "docker"
    state: present
  register: docker_post_step_1
  until: docker_post_step_1 is successful

- name: Adding user {{ USER }} to docker group
  become: true
  become_user: root
  user:
    name: "{{ USER }}"
    group: "docker"
    append: "yes"
  register: docker_post_step_2
  until: docker_post_step_2 is successful
  when: docker_post_step_1.changed

- name: Setting default shell
  become: true
  become_user: root
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  loop:
    - root
    - "{{ USER }}"
  register: fish_set_default
  until: fish_set_default is successful
