---
# APT (Debian/Ubuntu) packages
apt_keys:
  - https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  - https://dl.yarnpkg.com/debian/pubkey.gpg
  - https://download.docker.com/linux/ubuntu/gpg

apt_repos:
  - ppa:git-core/ppa
  - ppa:fish-shell/release-3
  - deb https://deb.nodesource.com/node_14.x focal main
  - deb https://dl.yarnpkg.com/debian/ stable main
  - "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_lsb.id|lower }} {{ ansible_lsb.codename|lower }} stable"

apt_items: # Security
  - iptables-persistent
  - netfilter-persistent
  # Fonts
  - fonts-firacode
  # Addinational tools
  - nodejs
  - python3-pip
  # Docker
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose

apt_force_items:
  - ripgrep

# Pacman/Manjaro Packages
pacman_packages:
  # Addinational tools
  - node
  # Docker
  - docker
  - docker-compose
  # Necessary tools
  - starship
  - bat
  - ripgrep

# Linked binaries
binaries:
  - name: fnm
    link: https://github.com/Schniz/fnm/releases/latest/download/fnm-linux.zip
    command: mv fnm-linux/fnm fnm
    binary: False
    direct: False
  - name: exa
    link: https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
    command: mv exa-linux-x86_64 exa
    binary: False
    direct: False
  - name: wrk
    link: https://github.com/dalisoft/wrk/releases/latest/download/wrk-linux.zip
    binary: False
    direct: True
