---
- name: Tap all Homebrew taps
  homebrew_tap:
    name: "{{ item }}"
  with_items: "{{ brew_mac_taps }}"
  register: install_brew_tap
  until: install_brew_tap is successful
  when:
    - INSTALL_MODE == 'DESKTOP'
    - item not in brew_tap_list.stdout_lines
  tags:
    - install-brew-taps

- name: Installing Homebrew packages for macOS
  homebrew:
    name: "{{ brew_mac_packages }}"
    state: latest
  register: install_brew_package
  until: install_brew_package is successful
  when:
    - INSTALL_MODE == 'DESKTOP'
    - ansible_os_family == 'Darwin'
  tags:
    - install-brew-packages
