---
# Homebrew Taps
- name: "List all Homebrew taps"
  command: brew tap
  register: brew_tap_list
  changed_when: false
  check_mode: false
  tags:
    - install-brew-taps

- name: Tap all Homebrew taps
  homebrew_tap:
    name: "{{ item }}"
  with_items: "{{ brew_taps }}"
  register: install_brew_tap
  until: install_brew_tap is successful
  when:
    - item not in brew_tap_list.stdout_lines
  tags:
    - install-brew-taps

# Homebrew packages
- name: Installing Homebrew packages
  homebrew:
    name: "{{ brew_packages }}"
    state: present
  register: install_brew_package
  until: install_brew_package is successful
  tags:
    - install-brew-packages

- import_tasks: debian/apt.yml
  when: ansible_os_family == 'Debian'
