---
# Homebrew Taps
- name: "List all Homebrew taps"
  command: brew tap
  register: brew_tap_list
  changed_when: false
  check_mode: false
  tags:
    - install-brew-taps

- name: Tap all Homebrew taps
  homebrew_tap:
    name: "{{ item }}"
  with_items: "{{ brew_taps }}"
  register: install_brew_tap
  until: install_brew_tap is successful
  when:
    - item not in brew_tap_list.stdout_lines
  tags:
    - install-brew-taps

# Homebrew packages
- name: Installing Homebrew packages
  homebrew:
    name: "{{ brew_packages }}"
    state: latest
  register: install_brew_package
  until: install_brew_package is successful
  tags:
    - install-brew-packages

- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

# Configure dotfiles (mackup)
- name: Configure dotfiles
  command: mackup restore -f
  register: install_dotfiles
  until: install_dotfiles is successful
  when:
    - initial_config_link is successful
  tags:
    - install-dot-files

- name: Install Neo-Vim plugins
  command: nvim -c "PlugInstall" -c "qa"
  register: install_vim_plugin
  until: install_vim_plugin is successful
  when:
    - install_dotfiles is successful
  tags:
    - install-vim-plugins
