---
  - name: Tap all Homebrew taps
    homebrew_tap:
      name:
        - homebrew/cask-fonts
        - heroku/brew
        - adoptopenjdk/openjdk
        - octave-app/octave-app
        - schniz/tap

  - name: Install Shell basics
    homebrew:
      name:
        - fish
        - starship
        - exa
        - bat
        - ripgrep
    #  state: present
    register: result
    until: result is successful
    when: homebrew_check.stat.exists

  - name: Install Git
    homebrew:
      name:
        - git
        - git-lfs
    register: result
    until: result is successful
    when: homebrew_check.stat.exists

  - name: Install terminal helper
    homebrew:
      name:
        - wget # For downloading some files
        - mackup # For sync configs across machines
        - htop # Monitoring manager
        - tmux # Terminal Multi-pleXer
        - wrk # Benchmark tool
        - cmake # Build tool
    register: result
    until: result is successful
    when: homebrew_check.stat.exists

  - name: Install Heroku
    homebrew:
      name: heroku
      state: present
    register: result
    until: result is successful
    when: homebrew_check.stat.exists

  - name: Install Programming Languages
    homebrew:
      name:
        - python
        - node
        - go
        - rust
        - llvm
    register: result
    until: result is successful
    when: homebrew_check.stat.exists

  - name: Install Ansible
    homebrew:
      name: ansible
      state: present
    register: result
    until: result is successful
    when: homebrew_check.stat.exists

  - name: Install Node.js helpers
    homebrew:
      name:
        - yarn
        - fnm
    register: result
    until: result is successful
    when: homebrew_check.stat.exists
