---
- name: macOS Common Playbook
  hosts: all
  become: false

  vars_files:
    - ../shared/vars.yml
    - vars.yml
  vars_prompt:
    - name: "HOME"
      prompt: "Please enter your HOME dir"

  environment:
    NPM_CONFIG_PREFIX: "{{ HOME }}/.npm-global"

  pre_tasks:
    # Pre-installation steps
    - import_tasks: ../shared/unix_pre-task.yml

  tasks:
    # Tasks list
    - import_tasks: tasks.yml
    # Post-installation
    - import_tasks: ../shared/unix_post-task.yml
    # Binary packages
    - import_tasks: ../shared/unix_binary-task.yml
      when: binaries is defined and binaries|length > 0
      tags:
        - install-binary-packages
