---
ensure_folders:
  - /usr/local/bin

# Initial files to link
initial_configs:
  # Files
  - .gitconfig
  - .gitignore
  - .nanorc
  # Folders
  - .nano

# Homebrew
# Homebrew taps
brew_taps:
  - schniz/tap

# Homebrew packages
brew_packages:
  - fnm
  - wrk
  # Build tools
  - openblas
  # Necessary tools
  - starship
  - bat
  - exa
  - ripgrep
  - ghostscript
