---
apt_keys:
  - https://dl.xanmod.org/gpg.key
  - https://keys.anydesk.com/repos/DEB-GPG-KEY
  - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
  - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

apt_repos:
  - deb http://deb.xanmod.org releases main
  - deb [arch=amd64] https://onepassword.s3.amazonaws.com/linux/debian edge main
  - deb http://deb.anydesk.com/ all main
  - deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main
  - deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ focal main

apt_items:
  # Improve Linux performance
  - linux-xanmod
  - intel-microcode
  - iucode-tool
  # PopOS polyfill
  - snapd
  - grub2-common
  - exfat-fuse
  - exfat-utils
  # Fonts
  - fonts-firacode
  # Programming languages
  # PHP
  - php
  - composer
  # Go
  - golang-go
  # Python
  - python3-pip
  - python3-pyqt5
  # Rust
  - rustc
  - cargo
  # Mobile-dev
  - gradle
  # Other desktop tools
  - ansible
  # For some GTK themes
  # and macOS Theme dependencies
  # for Linux
  - optipng
  - sassc
  - libcanberra-gtk-module
  - libglib2.0-dev
  # System utilities
  - timeshift
  # Utilities
  - kdiff3
  # Browsers
  - firefox
  - epiphany-browser
  # Most needed desktop apps
  - telegram-desktop
  - vlc
  - 1password
  - anydesk
  - octave
  - transmission
  # Editors
  - codium
  # KVM/Packages for Virtual Machines
  - qemu-kvm
  - virtinst
  - bridge-utils
  - cpu-checker
  # For AI Stuffs
  - nvidia-cuda-toolkit
  - nvidia-cuda-gdb
  - nvidia-cuda-dev
  - nvidia-cuda-doc
  # Java tools
  - adoptopenjdk-8-hotspot
