---
ensure_folders:
  - "~/.config/nvim"
  - "~/Desktop/config/dotfiles/.vim/autoload"
  - /etc/fail2ban

# Initial files to link
initial_configs:
  # Files
  - .vimrc
  # Folders
  - .vim

shared_packages:
  # Addinational terminal stuffs
  - htop
  - tmux
  - neovim
  # Build tools
  - unzip

npm_modules:
  - pm2
