---
- name: Linux Common Playbook
  hosts: all
  become: false

  vars_files:
    - ../shared/vars.yml
    - vars.yml
  vars_prompt:
    - name: "USER"
      prompt: "Please enter your User name"
      private: yes

  environment:
    NPM_CONFIG_PREFIX: "~/.npm-global"
    MOZ_USE_OMTC: 1
    PATH: "/usr/local/bin:$HOME/.local/bin:{{ ansible_env.PATH }}"

  tasks:
    # Tasks list

    # Installation
    - import_tasks: _manjaro.yml
      when: ansible_os_family == 'Archlinux'
    - import_tasks: _debian.yml
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
    # Post-installation
    - import_tasks: ../shared/unix_post-task.yml
    - import_tasks: post-task.yml
