---
- name: Linux Common Playbook
  hosts: all
  become: false

  vars_files:
    - ../shared/vars.yml
    - vars.yml
  vars_prompt:
    - name: "USER"
      prompt: "Please enter your User name"
      private: yes
    - name: "HOME"
      prompt: "Please enter your HOME dir"

  environment:
    NPM_CONFIG_PREFIX: "{{ HOME }}/.npm-global"
    MOZ_USE_OMTC: 1
    PATH: "/usr/local/bin:$HOME/.local/bin:{{ ansible_env.PATH }}"

  pre_tasks:
    # Pre-installation steps
    - import_tasks: ../shared/unix_pre-task.yml

  tasks:
    # Tasks list
    - import_tasks: tasks.yml
    # Post-installation
    - import_tasks: ../shared/unix_post-task.yml
    - import_tasks: post-task.yml
