---
# Docker Post-installation steps
- name: Create docker group
  group:
    name: "docker"
    state: present
  register: docker_post_step_1
  until: docker_post_step_1 is successful

- name: Adding user {{ USER }} to docker group
  become: true
  become_user: root
  user:
    name: "{{ USER }}"
    group: "docker"
    append: "yes"
  register: docker_post_step_2
  until: docker_post_step_2 is successful
  when: docker_post_step_1.changed

- name: Hide some applications
  become: true
  become_user: root
  lineinfile:
    path: "/usr/share/applications/{{ item }}.desktop"
    insertafter: "^Name= "
    line: NoDisplay=true
  loop:
    - nvim
    - openjdk-8-java
    - openjdk-8-policytool
    - groovyConsole
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
