---
- hosts: all

- name: Include macOS Common playbook
  import_playbook: ../../../common/os/mac/playbook.yml

- name: macOS Desktop Playbook
  hosts: all
  become: false
  roles:
    - appstore
  vars_files:
    - ../shared/vars.yml
    - vars.yml
  vars_prompt:
    - name: "USER"
      prompt: "Please enter your User name"
      private: yes
    - name: "SUDO_PASS"
      prompt: "Please enter your SUDO password"
      private: yes

  environment:
    NPM_CONFIG_PREFIX: "~/.npm-global"
    MOZ_USE_OMTC: 1

  pre_tasks:
    # Pre-installation steps
    - import_tasks: ../shared/unix_pre-task.yml

  tasks:
    - import_tasks: ../../../common/os/mac/tasks.yml
    - import_tasks: tasks.yml
    # Post-installation
    - import_tasks: ../shared/unix_post-task.yml
    - import_tasks: post-task.yml
    # Binary packages
    - import_tasks: ../../../common/os/shared/unix_binary-task.yml
      when: binaries is defined and binaries|length > 0
