---
# Installation
# Homebrew Taps
- name: "List all Homebrew taps"
  command: brew tap
  register: brew_tap_list
  changed_when: false
  check_mode: false
  tags:
    - install-brew-taps

- name: Tap all Homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_taps }}"
  register: install_brew_tap
  until: install_brew_tap is successful
  when:
    - item not in brew_tap_list.stdout_lines
  tags:
    - install-brew-taps

# Homebrew packages
- name: "List all Homebrew packages"
  command: brew ls
  register: brew_pkgs_list
  changed_when: false
  check_mode: false
  tags:
    - install-brew-packages

- name: Installing Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_packages }}"
  register: install_brew_package
  until: install_brew_package is successful
  when: item not in brew_pkgs_list.stdout_lines
  tags:
    - install-brew-packages

- name: "List installed Cask packages"
  command: brew cask list -1
  register: brew_cask_installed
  changed_when: false
  check_mode: false

# Homebrew Cask packages
- name: Installing Cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_cask_packages }}"
  register: install_brew_cask_package
  until: install_brew_cask_package is successful
  when: item not in brew_cask_installed.stdout_lines

- name: Installing Cask packages with ROOT permission
  become: true
  homebrew_cask:
    name: "{{ item }}"
    state: present
    sudo_password: "{{ SUDO_PASS }}"
  loop: "{{ brew_cask_packages_root }}"
  register: install_brew_cask_package
  until: install_brew_cask_package is successful
  when: item not in brew_cask_installed.stdout_lines
