---
- import_tasks: ../arch/main.yml
  when: ansible_os_family == 'Archlinux'
  tags:
    - install-archlinux-packages
- import_tasks: ../debian/main.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
  tags:
    - install-debian-packages

# Docker Post-installation steps
- name: Create docker group
  group:
    name: "docker"
    state: present
  register: docker_post_step_1
  until: docker_post_step_1 is successful

- name: Adding user {{ USER }} to docker group
  become: true
  become_user: root
  user:
    name: "{{ USER }}"
    group: "docker"
    append: "yes"
  register: docker_post_step_2
  until: docker_post_step_2 is successful
  when: docker_post_step_1.changed
