---
# VSCodium
- name: Linking VSCodium Settings on Linux
  file:
    src: ~/Desktop/config/dotfiles/Library/Application Support/VSCodium
    dest: "~/Desktop/config/dotfiles/.config/VSCodium"
    state: link
  retries: 1
  register: vscodium_debian_link
  until: vscodium_debian_link.attempts == 1

- name: Linking VSCodium Binary
  file:
    src: /usr/bin/codium
    dest: /usr/local/bin/code
    state: link
  retries: 1
  register: vscodium_debian_link
  until: vscodium_debian_link.attempts == 1

# Language Server binaries
- name: Installing Rust Analyzer Language Server on Linux
  get_url:
    url: https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux
    dest: /usr/local/bin/rust-analyzer
    mode: "0644"
  when: force_install is true or not reason_bin.stat.exists

- name: Downloading Reason Language Server on Linux
  get_url:
    url: https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux
    dest: ~/lsp/rls-linux.zip
  register: rls_zip
  when: force_install is true or not reason_bin.stat.exists

- name: Extracting Reason Language Server on Linux
  unarchive:
    src: rls-linux.zip
    dest: ~/lsp
  register: rls_unzip
  when: rls_zip.changed and force_install is true or not reason_bin.stat.exists

- name: Installing Reason Language Server on Linux
  copy:
    src: ~/lsp/rls-linux/reason-language-server
    dest: /usr/local/bin/reason-language-server
    mode: "0644"
  when: rls_unzip.changed and force_install is true or not reason_bin.stat.exists
