---
- name: APT Common Packages for Debian
  include_vars:
    name: apt_common
    file: common/debian/apt.yml
  when:
    - ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'

- name: APT Desktop-only Packages for Debian
  include_vars:
    name: apt_desktop
    file: desktop/debian/apt.yml
  when:
    - ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS'
    - INSTALL_MODE == 'DESKTOP'

- name: Prepare [APT] packages
  set_fact:
    apt_keys: "{{ (apt_common.apt_keys | default([])) + (apt_desktop.apt_keys | default([])) }}"
    apt_repos: "{{ (apt_common.apt_repos | default([])) + (apt_desktop.apt_repos | default([])) }}"
    apt_items: "{{ (apt_common.apt_items  | default([])) + (apt_desktop.apt_items | default([])) }}"
    apt_force_items: "{{ (apt_common.apt_force_items  | default([])) + (apt_desktop.apt_force_items | default([])) }}"
