---
- name: APT Common Packages for Debian
  include_vars:
    file: common/debian/apt.yml
  when:
    - ansible_os_family == 'Debian'

- name: APT Desktop-only Packages for Debian
  include_vars:
    file: desktop/debian/apt.yml
  when:
    - ansible_os_family == 'Debian'
    - INSTALL_MODE == 'DESKTOP'

- debug: var=apt_items
