---
- name: Common Binaries for Linux
  include_vars:
    name: bin_common_linux
    file: common/linux/bin.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS' or ansible_os_family == 'Archlinux'

- name: Desktop-only binaries for Linux
  include_vars:
    name: bin_desktop_linux
    file: desktop/linux/bin.yml
  when:
    - ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS' or ansible_os_family == 'Archlinux'
    - INSTALL_MODE == 'DESKTOP'

- name: Prepare binaries
  set_fact:
    binaries: "{{ (bin_common_linux.binaries | default([])) + (bin_desktop_linux.binaries | default([])) }}"
