---
- name: Homebrew common packages
  include_vars:
    file: common/brew.yml

- name: Homebrew Desktop-only packages for Debian
  include_vars:
    file: desktop/debian/brew.yml
  when:
    - ansible_os_family == 'Debian'
    - INSTALL_MODE == 'DESKTOP'

- name: Homebrew Desktop-only packages for Darwin
  include_vars:
    file: desktop/darwin/brew.yml
  when:
    - ansible_os_family == 'Darwin'
    - INSTALL_MODE == 'DESKTOP'
