---
brew_taps:
  - homebrew/cask-fonts
  - heroku/brew
  - adoptopenjdk/openjdk
  - octave-app/octave-app
  - schniz/tap

brew_packages:
  - fish
  - starship
  - exa
  - bat
  - ripgrep
  - nano
  - neovim
  - git
  - git-lfs
  - wget # For downloading some files
  - mackup # For sync configs across machines
  - htop # Monitoring manager
  - tmux # Terminal Multi-pleXer
  - wrk # Benchmark tool
  - cmake # Build tool
  - heroku
  - ansible
  - python
  - node
  - go
  - rust
  - llvm
  - yarn
  - fnm
  - docker
  - docker-compose

brew_cask_packages:
  - quicklook-json
  - qlcolorcode
  - qlstephen
  - qlmarkdown
  - qlimagesize
  - font-fira-code
  - brave-browser
  - macs-fan-control
  - telegram-desktop
  - the-unarchiver
  - firefox
  - folx
  - vlc
  - octave-app
  - postman
  - gitkraken
  - sublime-text
  - vscodium
  - clion
  - intellij-idea
  - datagrip
  - android-studio
  - krita
  - inkscape
  - betterzip

brew_cask_packages_root:
  #  - adguard
  - adoptopenjdk8
  #  - docker
