---
- name: Desktop Extensions
  include_vars:
    name: exts_desktop
    file: desktop/extensions.yml
  when:
    - INSTALL_MODE == 'DESKTOP'

- name: Loading Sublime Text variable from Debian
  include_vars:
    file: desktop/debian/extensions.yml
  when:
    - ansible_os_family == 'Debian' or ansible_os_family == 'Archlinux'
    - INSTALL_MODE == 'DESKTOP'

- name: Loading Sublime Text variable from Darwin
  include_vars:
    file: desktop/darwin/extensions.yml
  when:
    - ansible_os_family == 'Darwin'
    - INSTALL_MODE == 'DESKTOP'

- name: Prepare Extensions
  set_fact:
    vscodium_extensions: "{{ exts_desktop.vscodium_extensions | default([]) }}"
    sublime_extensions_git: "{{ exts_desktop.sublime_extensions_git | default([]) }}"
