---
- name: NPM Common modules
  include_vars:
    name: npm_common
    file: common/npm.yml

- name: NPM Desktop-only modules
  include_vars:
    name: npm_desktop
    file: desktop/npm.yml
  when:
    - INSTALL_MODE == 'DESKTOP'

- name: NPM Server-only modules
  include_vars:
    name: npm_server
    file: server/npm.yml
  when:
    - INSTALL_MODE == 'SERVER'

- name: Prepare [NPM] packages
  set_fact:
    npm_modules: "{{ (npm_common.npm_modules | default([])) + (npm_desktop.npm_modules | default([])) + (npm_server.npm_modules | default([])) }}"
    fnm_versions: "{{ (npm_common.fnm_versions | default([])) + (npm_desktop.fnm_versions | default([])) }}"
