---
# Import Snap packages as it's
# supported on Manjaro Linux
- import_tasks: ../../debian/tasks/ubuntu/snap.yml
  when:
    - INSTALL_MODE == 'DESKTOP'
    - ansible_distribution_major_version|int >= 18
  tags:
    - install-snap-packages

# Packman packages
- name: Installing Pacman packages
  become: true
  become_user: root
  pacman:
    name: "{{ pacman_packages }}"
    state: present
    update_cache: yes
  register: install_pacman_package
  until: install_pacman_package is successful
  tags:
    - install-pacman-package

# Docker Post-installation steps
- name: Create docker group
  group:
    name: "docker"
    state: present
  register: docker_post_step_1
  until: docker_post_step_1 is successful

- name: Adding user {{ USER }} to docker group
  become: true
  become_user: root
  user:
    name: "{{ USER }}"
    group: "docker"
    append: "yes"
  register: docker_post_step_2
  until: docker_post_step_2 is successful
  when: docker_post_step_1.changed

- name: Apply group change of docker
  shell: newgrp docker
  register: docker_post_step_3
  until: docker_post_step_3 is successful
  when: docker_post_step_2.changed
