---
- name: Adding apt keys
  become: true
  become_user: root
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ apt_keys }}"
  register: install_apt_key
  until: install_apt_key is successful

- name: Adding apt repositories
  become: true
  become_user: root
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repos }}"
  register: install_apt_repo
  until: install_apt_repo is successful

- name: "Update apt repositories"
  become: true
  become_user: root
  apt:
    update_cache: yes
  changed_when: false
  check_mode: false

- name: Installing optionless packages
  become: true
  become_user: root
  shell: 'apt install -o Dpkg::Options::="--force-overwrite" {{ apt_force_items }} -y'
  register: install_optionless_apt_package
  until: install_optionless_apt_package is successful

- name: Installing apt packages
  become: true
  become_user: root
  apt:
    name: "{{ apt_items }}"
    state: present
  register: install_apt_package
  until: install_apt_package is successful
