---
- name: "List installed Cask packages"
  command: brew cask list -1
  register: brew_cask_installed
  changed_when: false
  check_mode: false

- name: Installing Cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ brew_cask_packages }}"
  register: install_brew_cask_package
  until: install_brew_cask_package is successful
  when: item not in brew_cask_installed.stdout_lines

- name: Installing Cask packages with ROOT permission
  become: true
  homebrew_cask:
    name: "{{ item }}"
    state: present
    sudo_password: "{{ SUDO_PASS }}"
  with_items: "{{ brew_cask_packages_root }}"
  register: install_brew_cask_package
  until: install_brew_cask_package is successful
  when: item not in brew_cask_installed.stdout_lines
