---
- name: Installing Cask packages
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present
  register: install_brew_cask_package
  until: install_brew_cask_package is successful

- name: Installing Cask packages with ROOT permission
  become: true
  homebrew_cask:
    name: "{{ item }}"
    state: present
    sudo_password: "{{ SUDO_PASS }}"
  with_items: "{{ brew_cask_packages_root }}"
  register: install_brew_cask_package
  until: install_brew_cask_package is successful
