---
- name: Setting default shell
  become: true
  become_user: root
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  loop:
    - root
    - "{{ USER }}"
  register: fish_set_default
  until: fish_set_default is successful

# VSCode
- name: Linking VSCode Settings on Linux
  file:
    src: "~/Desktop/config/dotfiles/Library/Application Support/Code"
    dest: "~/Desktop/config/dotfiles/.config/Code"
    state: link
  retries: 1
  register: vscode_debian_link
  until: vscode_debian_link.attempts == 1

- name: Hide some applications
  become: true
  become_user: root
  lineinfile:
    path: "/usr/share/applications/{{ item }}.desktop"
    insertafter: "^Name= "
    line: NoDisplay=true
  loop:
    - nvim
    - openjdk-8-java
    - openjdk-8-policytool
    - groovyConsole
  when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'Pop!_OS'
