---
binaries:
  - name: exa
    link: https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
    command: mv exa-linux-x86_64 exa
    binary: False
    direct: False

# Linux shared package names
# Shared names (DRY method)
shared_packages:
  # Browsers
  - epiphany-browser
  - firefox
  # Most needed desktop apps
  - 1password
  - vlc
  - telegram-desktop
  - octave
  - qbittorrent
  - github-desktop
  # Development tools
  - postman
  - datagrip
  # Editors
  - code
  # System utilities
  - gparted
  - speedify
  # KVM/Packages for Virtual Machines
  - bridge-utils
  # Tools
  - obs-studio
  - android-file-transfer

# APT (Debian/Ubuntu) packages
apt_keys:
  - https://keys.anydesk.com/repos/DEB-GPG-KEY
  - https://dl.google.com/linux/linux_signing_key.pub
  - https://packages.microsoft.com/keys/microsoft.asc
  - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
  - https://packagecloud.io/shiftkey/desktop/gpgkey
  - https://get.speedify.com/pgp.key
  - https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc
  - https://cli-assets.heroku.com/apt/release.key

apt_ring_keys:
  - keyserver: keyserver.ubuntu.com
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

apt_repos:
  - ppa:obsproject/obs-studio
  - ppa:maarten-fonville/android-studio
  - ppa:tiagohillebrandt/postman
  - ppa:qbittorrent-team/qbittorrent-stable
  - ppa:samoilov-lex/aftl-stable
  - ppa:libreoffice/libreoffice-7-0
  - ppa:noobslab/apps
  - deb https://onepassword.s3.amazonaws.com/linux/debian edge main
  - deb http://deb.anydesk.com/ all main
  - deb http://dl.google.com/linux/chrome/deb/ stable main
  - deb https://packages.microsoft.com/repos/vscode stable main
  - "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ ansible_lsb.codename|lower }} main"
  - deb https://packagecloud.io/shiftkey/desktop/any/ any main
  - deb http://apt.connectify.me/ speedify main
  - deb http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com bionic main
  - deb https://cli-assets.heroku.com/apt

apt_items:
  # PopOS polyfill
  - snapd
  - grub2-common
  - exfat-fuse
  - exfat-utils
  - software-properties-common
  - apt-transport-https
  # Python
  - python3-pyqt5
  # System utilities
  - flameshot
  - heroku
  # Most needed desktop apps
  - anydesk
  - xdman
  # Browser
  - google-chrome-stable
  # Mobile dev
  - android-studio-4.1
  # Office tools
  - libreoffice
  # KVM/Packages for Virtual Machines
  - qemu
  - qemu-kvm
  - qemu-system
  - qemu-utils
  - libvirt-clients
  - libvirt-daemon
  - libvirt-daemon-system
  - virtinst
  - virt-manager
  - bridge-utils
  - cpu-checker
  # For AI Stuffs
  - nvidia-cuda-toolkit
  - nvidia-cuda-gdb
  - nvidia-cuda-dev
  - nvidia-cuda-doc
  # Java tools
  - adoptopenjdk-14-hotspot
  # Dependencies for WebRTC
  - libavdevice-dev
  - libavfilter-dev
  - libopus-dev
  - libvpx-dev
  - libsrtp2-dev
  - pkg-config

# Snap packages
snap_packages:
  - starship

snap_classic_packages:
  - deno
  - gitkraken
  - clockify-cli
  - ora

# Pacman packages
pacman_packages:
  # Polyfills
  - exfat-dkms-git
  # Fonts
  - ttf-fira-code
  # Other desktop tools
  - heroku-cli
  # Most needed desktop apps
  - flameshot-git
  - anydesk-bin
  - google-chrome
  # Utilities
  - clockify-desktop
  # Development tools
  - gitkraken
  - freedownloadmanager
  # Editors / IDE
  - android-studio
  # Office tools
  - libreoffice-fresh
  # Messengers
  - slack-desktop
  # KVM/Packages for Virtual Machines
  - virt-manager
  - qemu
  - qemu-arch-extra
  - vde2
  - iptables
  - ebtables
  - ovmf
  - dnsmasq
  - bridge-utils
  - openbsd-netcat
  # For AI Stuffs
  - cuda
  # Java tools
  - jdk14-adoptopenjdk
  # Python tools
  - anaconda
