---
st_packages_dir: "~/.config/sublime-text-3/Packages"

binaries:
  - name: exa
    link: https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
    command: mv exa-linux-x86_64 exa
    binary: False
    direct: False
  - name: rust-analyzer
    link: https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux
    direct: False
    binary: True

# Linux shared package names
# Shared names (DRY method)
shared_packages:
  # PHP
  - php
  - composer
  # Mobile-dev
  - gradle
  # Browsers
  - epiphany-browser
  - firefox
  # Most needed desktop apps
  - 1password
  - vlc
  - telegram-desktop
  - octave
  # Editors
  - sublime-text
  - code
  # System utilities
  - gparted
  # KVM/Packages for Virtual Machines
  - bridge-utils

# APT (Debian/Ubuntu) packages
apt_keys:
  # - https://dl.xanmod.org/gpg.key
  - https://keys.anydesk.com/repos/DEB-GPG-KEY
  - https://packages.microsoft.com/keys/microsoft.asc
  - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
  - https://packagecloud.io/shiftkey/desktop/gpgkey

apt_ring_keys:
  - keyserver: keyserver.ubuntu.com
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

apt_repos:
  # - deb http://deb.xanmod.org releases main
  - deb https://onepassword.s3.amazonaws.com/linux/debian edge main
  - deb http://deb.anydesk.com/ all main
  - deb https://packages.microsoft.com/repos/vscode stable main
  - "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ ansible_lsb.codename|lower }} main"
  - deb [arch=amd64] https://packagecloud.io/shiftkey/desktop/any/ any main

apt_items:
  # Improve Linux performance
  # - linux-xanmod
  # - intel-microcode
  # - iucode-tool
  # PopOS polyfill
  - snapd
  - grub2-common
  - exfat-fuse
  - exfat-utils
  - software-properties-common
  - apt-transport-https
  # Programming languages
  # Go
  - golang-go
  # Python
  - python3-pip
  - python3-pyqt5
  # Rust
  - rustc
  - cargo
  # For some GTK themes
  # and macOS Theme dependencies
  # for Linux
  - optipng
  - sassc
  - libcanberra-gtk-module
  - libglib2.0-dev
  # System utilities
  - timeshift
  - flameshot
  # Most needed desktop apps
  - anydesk
  - transmission
  # Browser
  - chromium-browser
  - github-desktop
  # KVM/Packages for Virtual Machines
  - qemu
  - qemu-kvm
  - qemu-system
  - qemu-utils
  - libvirt-clients
  - libvirt-daemon
  - libvirt-daemon-system
  - virtinst
  - virt-manager
  - bridge-utils
  - cpu-checker
  # For AI Stuffs
  - nvidia-cuda-toolkit
  - nvidia-cuda-gdb
  - nvidia-cuda-dev
  - nvidia-cuda-doc
  # Java tools
  - adoptopenjdk-8-hotspot
  # Dependencies for WebRTC
  - libavdevice-dev
  - libavfilter-dev
  - libopus-dev
  - libvpx-dev
  - libsrtp2-dev
  - pkg-config

apt_force_items:
  - bat

# Snap packages
snap_packages:
  - starship
  - beekeeper-studio
  - postman
  - insomnia
  - insomnia-designer

snap_classic_packages:
  - heroku
  - gitkraken
  - webstorm
  - pycharm
  - android-studio

# Pacman packages
pacman_packages:
  # Improve Linux performance
  - linux-manjaro-xanmod
  # Polyfills
  - exfat-dkms-git
  # Fonts
  - ttf-fira-code
  # Programming languages
  # Go
  - go
  # Python
  - python
  # Rust
  - rust
  # Other desktop tools
  - heroku-cli
  # For some GTK themes
  # and macOS Theme dependencies
  # for Linux
  - krita
  - inkscape
  - optipng
  - sassc
  - gtk-engine-murrine
  - gtk-engines
  # Most needed desktop apps
  - flameshot-git
  - anydesk-bin
  - chromium
  - uget
  - notion-app
  - transmittion-gtk
  # Development tools
  - beekeeper-studio-appimage
  - mongotron-bin
  - gitkraken
  - postman
  - insomnia-bin
  - insomnia-designer-bin
  - github-desktop
  # Editors / IDE
  - webstorm
  - pycharm
  - android-studio
  # KVM/Packages for Virtual Machines
  - virt-manager
  - qemu
  - qemu-arch-extra
  - vde2
  - iptables
  - ebtables
  - ovmf
  - dnsmasq
  - bridge-utils
  - openbsd-netcat
  # For AI Stuffs
  - cuda
  # Java tools
  - jdk8-adoptopenjdk
