---
st_packages_dir: "~/.config/sublime-text-3/Packages"

binaries:
  - name: exa
    link: https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
    command: mv exa-linux-x86_64 exa
    binary: False
    direct: False
  - name: rust-analyzer
    link: https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-linux
    direct: False
    binary: True
  - name: reason-language-server
    link: https://github.com/jaredly/reason-language-server/releases/latest/download/rls-linux.zip
    command: mv rls-linux/reason-language-server reason-language-server
    direct: False
    binary: False
  - name: dprint
    link: https://github.com/dprint/dprint/releases/latest/download/dprint-x86_64-unknown-linux-gnu.zip
    direct: True
    binary: False

# Linux shared package names
# Shared names (DRY method)
shared_packages:
  # Browsers
  - epiphany-browser
  - firefox
  # Most needed desktop apps
  - 1password
  - vlc
  - telegram-desktop
  - octave
  # Editors
  - sublime-text
  - code
  # System utilities
  - gparted
  - speedif
  # KVM/Packages for Virtual Machines
  - bridge-utils
  # Tools
  - obs-studio

# APT (Debian/Ubuntu) packages
apt_keys:
  - https://keys.anydesk.com/repos/DEB-GPG-KEY
  - https://dl.google.com/linux/linux_signing_key.pub
  - https://packages.microsoft.com/keys/microsoft.asc
  - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

apt_ring_keys:
  - keyserver: keyserver.ubuntu.com
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

apt_repos:
  - ppa:obsproject/obs-studio
  - deb https://onepassword.s3.amazonaws.com/linux/debian edge main
  - deb http://deb.anydesk.com/ all main
  - deb http://dl.google.com/linux/chrome/deb/ stable main
  - deb https://packages.microsoft.com/repos/vscode stable main
  - "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ ansible_lsb.codename|lower }} main"

apt_items:
  # PopOS polyfill
  - snapd
  - grub2-common
  - exfat-fuse
  - exfat-utils
  - software-properties-common
  - apt-transport-https
  # Python
  - python3-pyqt5
  # System utilities
  - flameshot
  # Most needed desktop apps
  - anydesk
  - transmission
  # Browser
  - google-chrome-stable
  # KVM/Packages for Virtual Machines
  - qemu
  - qemu-kvm
  - qemu-system
  - qemu-utils
  - libvirt-clients
  - libvirt-daemon
  - libvirt-daemon-system
  - virtinst
  - virt-manager
  - bridge-utils
  - cpu-checker
  # For AI Stuffs
  - nvidia-cuda-toolkit
  - nvidia-cuda-gdb
  - nvidia-cuda-dev
  - nvidia-cuda-doc
  # Java tools
  - adoptopenjdk-8-hotspot
  # Dependencies for WebRTC
  - libavdevice-dev
  - libavfilter-dev
  - libopus-dev
  - libvpx-dev
  - libsrtp2-dev
  - pkg-config

# Snap packages
snap_packages:
  - starship
  - android-file-transfer-linux
  - postman

snap_classic_packages:
  - deno
  - heroku
  - gitkraken
  - android-studio

# Pacman packages
pacman_packages:
  # Polyfills
  - exfat-dkms-git
  # Fonts
  - ttf-fira-code
  # Other desktop tools
  - heroku-cli
  - android-file-transfer
  # Most needed desktop apps
  - flameshot-git
  - anydesk-bin
  - google-chrome
  - uget
  - transmittion-gtk
  # Development tools
  - gitkraken
  - postman
  # Editors / IDE
  - android-studio
  # KVM/Packages for Virtual Machines
  - virt-manager
  - qemu
  - qemu-arch-extra
  - vde2
  - iptables
  - ebtables
  - ovmf
  - dnsmasq
  - bridge-utils
  - openbsd-netcat
  # For AI Stuffs
  - cuda
  # Java tools
  - jdk15-adoptopenjdk
  # Python tools
  - anaconda
