---
# FNM Versions
- name: "List installed fnm versions"
  command: fnm ls
  register: fnmv_list
  changed_when: false
  check_mode: false
  tags:
    - install-fnm-version

- name: Installing fnm version
  shell: "fnm install {{ item }}"
  with_items: "{{ fnm_versions }}"
  register: install_fnm_version
  until: install_fnm_version is successful
  when:
    - item not in fnmv_list.stdout
  tags:
    - install-fnm-version

# NPM Modules
- name: Installing npm modules
  npm:
    global: "yes"
    path: ~/.npm-global
    name: "{{ item }}"
    state: latest
  with_items: '{{ npm_modules }}'
  register: install_npm_package
  until: install_npm_package is successful
  tags:
    - install-npm-modules

# PIP Modules
- name: Installing pip modules
  pip:
    name: "{{ pip_modules }}"
    state: latest
    executable: pip3
  register: install_pip_module
  until: install_pip_module is successful
  when:
    - homebrew_check.stat.exists
  tags:
    - install-pip-modules
