---
# NPM Modules
- name: "List installed npm modules"
  command: npm ls -g --depth=0
  register: npm_modules_list
  changed_when: false
  check_mode: false
  tags:
    - install-npm-modules

- name: Installing npm modules
  npm:
    global: yes
    path: ~/.npm-global
    name: "{{ item }}"
    state: latest
  with_items: "{{ npm_modules }}"
  register: install_npm_package
  until: install_npm_package is successful
  when:
    - homebrew_check.stat.exists
    - item not in npm_modules_list.stdout
  tags:
    - install-npm-modules

# PIP Modules
- name: "List installed pip modules"
  command: pip3 list
  register: pip_modules_list
  changed_when: false
  check_mode: false
  tags:
    - install-pip-modules

- name: Installing pip modules
  pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items: "{{ pip_modules }}"
  register: install_pip_module
  until: install_pip_module is successful
  when:
    - homebrew_check.stat.exists
    - item not in pip_modules_list.stdout_lines
  tags:
    - install-pip-modules
