---
dependencies:
  - role: geerlingguy.mas
    vars:
      mas_signin_dialog: false
      mas_upgrade_all_apps: false
      mas_installed_apps:
        - id: 1464122853
          name: NextDNS
        - id: 999025824
          name: Speedify VPN
        - id: 816239782
          name: Joxi
        - id: 425424353
          name: The Unarchiver
        - id: 1515213004
          name: Session Pal
        # - id: 425264550
        #  name: Blackmagic SSD Speed test
        # - id: 1466185689
        #  name: Blackmagic RAW Speed test
        - id: 1322465647
          name: Telegram macOS
        - id: 803453959
          name: Slack
        - id: 1333542190
          name: 1Password
        - id: 1037126344
          name: Apple Configurator 2
        - id: 1450874784
          name: Transporter
        - id: 640199958
          name: Apple Developer
        - id: 408981434
          name: iMovie
        # - id: 571213070
        #  name: DeVinci Resolve
        - id: 409201541
          name: Pages
        - id: 409183694
          name: Keynote
        - id: 409203825
          name: Numbers
        - id: 1399498094
          name: Websocket Client
        - id: 1459055246
          name: Noto
        - id: 497799835
          name: XCode
