---
- name: Ensuring Homebrew Is Installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
  fail:
    msg: Homebrew is missing...Install from http://brew.sh/
  when:
    - not homebrew_check.stat.exists
    - not install_homebrew_if_missing

- name: Installing Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when:
    - not homebrew_check.stat.exists
    - install_homebrew_if_missing

- name: Check vim-plug
  stat:
    path: ~/Desktop/config/dotfiles/vim/autoload/plug.vim
  register: vim_plug_file
  tags:
    - link-initial-config

- name: Download vim-plug
  shell:
    curl -fLo ~/Desktop/config/dotfiles/vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  when:
    - force_install is true or not vim_plug_file.stat.exists
  tags:
    - link-initial-config

- name: Linking initial configs
  file:
    src: "~/Desktop/config/dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    state: link
    force: no
  with_items: "{{ initial_configs }}"
  retries: 1
  register: initial_config_link
  until: initial_config_link.attempts == 1
  tags:
    - link-initial-config
