---
- name: My Machine Configurations
  hosts: all
  become: false
  roles:
    - common
    - darwin
    - modules
    - links

  vars_prompt:
    - name: "INSTALL_MODE"
      prompt: "Please enter your Install Mode [DESKTOP or SERVER]"
      private: yes
    - name: "USER"
      prompt: "Please enter your User name"
      private: yes
    - name: "HOME"
      prompt: "Please enter your HOME dir"
    - name: "SUDO_PASS"
      prompt: "Please enter your SUDO password"
      private: yes

  environment:
    NPM_CONFIG_PREFIX: "{{ HOME }}/.npm-global"
    NFANCURVE_PATH: "$HOME/nfancurve"
    PATH: "/usr/local/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/snap/bin:$HOME/.local/bin:{{ ansible_env.PATH }}"
    MOZ_USE_OMTC: 1

  vars:
    install_homebrew_if_missing: true
    force_install: false

    ensure_folders:
      - .vim/autoload
      - .config/nvim
      - .config/autostart

    initial_configs:
      # Files
      - .gitconfig
      - .gitignore
      - .mackup.cfg
      - .nanorc
      - .vimrc
      # Folders
      - .vim
      - .config/nvim
      - .config/autostart
      - .nano
      - nfancurve

  pre_tasks:
    - import_tasks: pre-tasks.yml
    # Import variables as tasks
    - import_tasks: vars/brew.yml
    - import_tasks: vars/binaries.yml
    - import_tasks: vars/apt.yml
    - import_tasks: vars/pacman.yml
    - import_tasks: vars/snap.yml
    - import_tasks: vars/npm.yml
    - import_tasks: vars/pip.yml
    - import_tasks: vars/extensions.yml

  tasks:
    # Import tasks
    - import_tasks: roles/linux/tasks/main.yml
      when:
        - ansible_os_family == 'Debian' or ansible_os_family == 'Pop!_OS' or ansible_os_family == 'Archlinux'
    # Disable extensions currently
    # See https://github.com/VSCodium/vscodium/issues/424 for issue
    # See https://github.com/VSCodium/vscodium/issues/430#issuecomment-646312604
    # or https://github.com/VSCodium/vscodium/issues/418#issuecomment-659257713 # (recommended) for temporarily solution
    - import_tasks: roles/extensions/tasks/main.yml
      when:
        - INSTALL_MODE == 'DESKTOP'
