---
- name: My Machine Configurations
  hosts: all
  become: false
  roles:
    - common
    - darwin
    - debian
    - modules
    - extensions

  vars_prompt:
    - name: "INSTALL_MODE"
      prompt: "Please enter your Install Mode [DESKTOP or SERVER]"
      private: yes
    - name: "USER"
      prompt: "Please enter your User name"
      private: yes
    - name: "SUDO_PASS"
      prompt: "Please enter your SUDO password"
      private: yes

  vars:
    install_homebrew_if_missing: true
    force_install: false

    initial_configs:
    # Files
      - .gitconfig
      - .mackup.cfg
      - .nanorc
      - .vimrc
    # Folders
      - .vim
      - .config/nvim
      - .nano

  pre_tasks:
    - import_tasks: pre-tasks.yml
    # Import variables as tasks
    - import_tasks: vars/brew.yml
    - import_tasks: vars/apt.yml
    - import_tasks: vars/snap.yml
    - import_tasks: vars/npm.yml
    - import_tasks: vars/pip.yml
    - import_tasks: vars/extensions.yml

