---
- name: My Machine Configurations
  hosts: all
  become: "no"
  roles:
    - common
    - mas
    - modules

  vars_prompt:
    - name: "SUDO_PASS"
      prompt: "Please enter your SUDO password"
      private: "yes"

  vars_files:
    - vars/brew.yml
    - vars/snap.yml
    - vars/npm.yml
    - vars/pip.yml
    - vars/editor_extensions.yml

  vars:
    install_homebrew_if_missing: true
    force_install: false

    initial_configs:
      - .gitconfig
      - .mackup.cfg
      - .nanorc
      - .vimrc

    initial_folders:
      - .vim
      - .config/nvim
      - .nano

  pre_tasks:
    - import_tasks: pre-tasks.yml

  tasks:
    - import_tasks: mac-casks.yml
      when:
        - ansible_os_family == 'Darwin'
      tags:
        - install-brew-cask-packages
    - import_tasks: snap.yml
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version|int >= 18
      tags:
        - install-snap-packages
    - import_tasks: roles/editor_extensions/tasks/main.yml
      tags:
        - install-editor-extensions
