---
- name: Include macOS Common playbook
  import_playbook: ../../../common/os/mac/playbook.yml

- name: macOS Desktop Playbook
  hosts: all
  become: false
  gather_facts: yes
  roles:
    - appstore
  vars_files:
    - ../shared/vars.yml
    - vars.yml
  vars_prompt:
    - name: "USER"
      prompt: "Please enter your User name"
      private: yes
    - name: "SUDO_PASS"
      prompt: "Please enter your SUDO password"
      private: yes

  environment:
    NPM_CONFIG_PREFIX: "~/.npm-global"

  pre_tasks:
    # Pre-installation steps
    - import_tasks: ../../../common/os/shared/pre-task.yml

  tasks:
    - import_tasks: ../../../common/os/mac/tasks.yml
    - import_tasks: tasks.yml
    # Post-installation
    - import_tasks: ../../../common/os/shared/post-task.yml
    - import_tasks: ../shared/post-task.yml
