---
- name: List installed Cask packages
  command: brew list --cask -1
  register: brew_cask_installed
  changed_when: false
  check_mode: false

# Homebrew Cask packages
- name: Installing Cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_cask_packages }}"
  register: install_brew_cask_package
  until: install_brew_cask_package is successful
  when: item not in brew_cask_installed.stdout_lines

- name: Installing Cask packages with ROOT permission
  become: yes
  homebrew_cask:
    name: "{{ item }}"
    state: present
    sudo_password: "{{ SUDO_PASS }}"
  loop: "{{ brew_cask_packages_root }}"
  register: install_brew_cask_package
  until: install_brew_cask_package is successful
  when: item not in brew_cask_installed.stdout_lines

# Gems packages
- name: Install Gems
  gem:
    name: "{{ item }}"
    state: present
    user_install: yes
  loop:
    - cocoapods
  tags:
    - install-gem-packages
