---
# Homebrew taps
brew_taps:
  - heroku/brew
  - dprint/dprint
  - homebrew/cask-fonts
  - adoptopenjdk/openjdk
  - octave-app/octave-app

# Homebrew packages
brew_packages:
  - pyqt
  # PL Essentials
  - rust-analyzer
  - cocoapods
  # Other desktop tools
  - dprint
  - heroku
  # Tools / Dependencies
  - watchman

brew_cask_packages:
  # macOS QuickLook plugins
  - qlcolorcode
  - qlstephen
  - qlmarkdown
  - qlimagesize
  # Fonts
  - font-fira-code
  # Utilities
  - the-unarchiver
  - appcleaner
  - kdiff3
  - android-file-transfer
  - obs
  - anydesk
  - clockify
  # VPN
  - speedify
  - lulu
  # Browsers
  - firefox
  - google-chrome
  # Most needed desktop apps
  - 1password
  - vlc
  - notion
  # Messengers
  - telegram
  - slack
  - octave-app
  # Git App
  - gitkraken
  # Download managers
  - folx
  # Development tools
  - postman
  - datagrip
  # Editors
  - visual-studio-code
  - android-studio

brew_cask_packages_root:
  - adoptopenjdk/openjdk/adoptopenjdk11
  - anaconda
  - adguard
  - cloudflare-warp
  - docker
  # - vmware-fusion # M1 Support not available, see https://communities.vmware.com/t5/VMware-Fusion-Discussions/vmware-fusion-on-m1-goal/m-p/2837097#M173227
  #- anka-virtualization # Waiting for M1 support
