---
st_packages_dir: "~/Library/Application Support/Sublime Text 3/Packages"

binaries:
  - name: reason-language-server
    link: https://github.com/jaredly/reason-language-server/releases/latest/download/rls-linux.zip
    command: mv rls-linux/reason-language-server reason-language-server
    direct: False
    binary: False

# Homebrew
# Homebrew taps
brew_taps:
  - heroku/brew
  - dprint/dprint
  - homebrew/cask-fonts
  - adoptopenjdk/openjdk
  - octave-app/octave-app

# Homebrew packages
brew_packages:
  - pyqt
  # PL Essentials
  - rust-analyzer
  # Other desktop tools
  - dprint
  - heroku

brew_cask_packages:
  # macOS QuickLook plugins
  - qlcolorcode
  - qlstephen
  - qlmarkdown
  - qlimagesize
  # Fonts
  - font-fira-code
  # Utilities
  - the-unarchiver
  - appcleaner
  - kdiff3
  - android-file-transfer
  - altserver
  - obs
  - adguard
  - cloudflare-warp
  - anydesk
  # Browsers
  - firefox
  - google-chrome
  # Most needed desktop apps
  - 1password
  - vlc
  - telegram
  - octave-app
  - gitkraken
  - folx
  - qbittorrent
  # Development tools
  - postman
  - datagrip
  # Editors
  - sublime-text
  - visual-studio-code
  - android-studio

brew_cask_packages_root:
  - adoptopenjdk/openjdk/adoptopenjdk14
  - anaconda
  - docker
  - vmware-fusion
  - anka-virtualization
