---
# Import Snap packages as it's
# supported on Manjaro Linux
- import_tasks: ../ubuntu/snap.yml
  when:
    - INSTALL_MODE == 'DESKTOP'
    - ansible_distribution_major_version|int >= 18
  tags:
    - install-snap-packages

# Packman packages
- name: Installing Pacman packages
  become: true
  become_user: root
  pacman:
    name: "{{ pacman_packages }}"
    state: present
    update_cache: yes
  register: install_pacman_package
  until: install_pacman_package is successful
  tags:
    - install-pacman-package
