---
# Packman packages
- name: Installing Pacman packages
  become: true
  become_user: root
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ pacman_packages }}"
  register: install_pacman_package
  until: install_pacman_package is successful
  tags:
    - install-pacman-package
